# Generated by Django 3.2.3 on 2021-07-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrequest',
            name='kerbero_id',
            field=models.IntegerField(verbose_name='個体ID'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='kerbero_id',
            field=models.IntegerField(verbose_name='個体ID'),
        ),
    ]
