# Generated by Django 3.2.3 on 2021-07-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210710_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='second_end_time',
            new_name='center_end_time',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='second_head_name',
            new_name='center_head_name',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='second_start_time',
            new_name='center_start_time',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='first_end_time',
            new_name='left_end_time',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='first_head_name',
            new_name='left_head_name',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='first_start_time',
            new_name='left_start_time',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='third_end_time',
            new_name='right_end_time',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='third_head_name',
            new_name='right_head_name',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='third_start_time',
            new_name='right_start_time',
        ),
    ]
