# Generated by Django 3.2.3 on 2021-07-10 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210710_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='center_head_name',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='left_head_name',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='right_head_name',
        ),
    ]
